# Generated by Django 6.1 on 2026-08-28 04:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('short_description', models.CharField(blank=True, help_text="Short line shown under the room name, e.g. 'Comfortable layout, free WiFi'.", max_length=255)),
                ('amenities', models.TextField(blank=True, help_text='One amenity per line, e.g.\nWorkspace\nAir-conditioning\nFree WiFi, TV')),
                ('price', models.DecimalField(decimal_places=2, help_text='Current nightly rate in Naira (₦).', max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional original price to show struck through, for promos/discounts.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this room from the site without deleting it.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Optional, not shown publicly.', max_length=254)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(max_length=2000)),
                ('is_approved', models.BooleanField(default=True, help_text='Untick to hide this review from the public site without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, help_text='Optional — leave blank for a general hotel review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='hotel.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.room')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
